plugins {
    id 'com.android.application'
}

android {
    namespace 'com.greenman.hedgewitchery.stocktake'
    compileSdk 35

    defaultConfig {
        applicationId 'com.greenman.hedgewitchery.stocktake'
        minSdk 29
        targetSdk 35
        versionCode 10
        versionName 'V8-CLEAN-1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
